management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"

  endpoint:
    metrics:
      enabled: true
    health:
      enabled: true
      show-details: always
    logfile:
      enabled: true

logging:
  file:
    name: app.log

spring:
  main.allow-circular-references: true

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml