spring:
  main.allow-circular-references: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}

  jpa:
    generate-ddl: ${JPA_GENERATE_DDL:false}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:/db/changelog/db.changelog-master.xml}